name: "buzz-services"

services:
  database:
    image: mysql:8.4
    restart: on-failure
    pull_policy: if_not_present
    environment:
      MYSQL_DATABASE: "buzz"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - type: volume
        source: db-data
        target: /mysql


volumes:
  db-data: