name: Deploy Backend to AWS

on:
 push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker CLI
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to Docker Hub or another registry where you push images
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image for backend
      - name: Build and push backend Docker image
        env:
          TAG: ${{ github.sha }}
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/buzz:${{ secrets.TAG }} -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}buzz:${{ secrets.TAG }}
